### ISSUE TITLE
hello, an error appears when trying to open the model

### ISSUE THREAD

**Issue by masquit** [alphazolam/fmt_RE_MESH-Noesis-Plugin#2]
Model:
...\re_chunk_000\natives\stm\environment\stage\resource\st11\st11_012_elevatorhall_in2f\st11_012_elevatorhall_in2focc.mesh.2101050001
Error:
Traceback (most recent call last):
  File "Z:\!!ResidentEvek8_RES\noesisv4466\plugins\python\fmt_RE_MESH.py", line 2551, in meshLoadModel
    mdlList = mesh.loadMeshFile(mdlList)
  File "Z:\!!ResidentEvek8_RES\noesisv4466\plugins\python\fmt_RE_MESH.py", line 2540, in loadMeshFile
    for i, bone in enumerate(mdl.bones):
UnboundLocalError: local variable 'mdl' referenced before assignment

**Comment by alphazolam** [comment]
that's an occluder mesh. They are simple primitive meshes for controlling how light affects an object, usually terrain. I might look into adding more support for those soon, but they are generally not very important for ripping nor modding from what I've seen so far
